In [3]:
import sqlalchemy
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session #sessionmaker
from sqlalchemy import create_engine, inspect
from sqlalchemy import Column, Integer, String

import pandas as pd
import numpy as np

In [5]:
engine = create_engine('sqlite:///../data/football_new.db')

Base = automap_base()
Base.prepare(engine, reflect=True)

#cfb_positions = Base.classes.cfb_positions
#cfb_recruits = Base.classes.cfb_recruits
#nfl_draft = Base.classes.nfl_draft
#nfl_positions = Base.classes.nfl_positions
#nfl_teams = Base.classes.nfl_teams

session = Session(engine)
inspector = inspect(engine)

In [6]:
recruits = pd.read_sql_table('cfb_recruits', engine)
draftees = pd.read_sql_table('nfl_draft', engine)

In [7]:
draftees.head(1)

   YEAR  RND  PICK            PLAYER FIRST_NAME LAST_NAME   TM POS   SCHOOL
0  2009    1     1  Matthew Stafford    Matthew  Stafford  DET  QB  Georgia

In [20]:
results = session.query(cfb_recruits, nfl_draft).filter(cfb_recruits.FIRST_NAME == nfl_draft.FIRST_NAME).filter(cfb_recruits.LAST_NAME == nfl_draft.LAST_NAME)

In [29]:
draftees['PLAYER'] = draftees['FIRST_NAME'] + ' ' + draftees['LAST_NAME']
draftees.head()

,PRIMARY_KEY,YEAR,RND,PICK,FIRST_NAME,LAST_NAME,TM,POS,SCHOOL,PLAYER
0,1,2009,1,1,Matthew,Stafford,DET,QB,Georgia,Matthew Stafford
1,2,2009,1,2,Jason,Smith,STL,T,Baylor,Jason Smith
2,3,2009,1,3,Tyson,Jackson,KAN,DE,LSU,Tyson Jackson
3,4,2009,1,4,Aaron,Curry,SEA,LB,Wake Forest,Aaron Curry
4,5,2009,1,5,Mark,Sanchez,NYJ,QB,USC,Mark Sanchez

In [30]:
recruits.head()

,PRIMARY_KEY,PLAYER,FIRST_NAME,LAST_NAME,POS,YEAR,RNK,STAR,247_SCORE,COLLEGE,CITY,STATE,LAT,LNG,HIGH_SCHOOL
0,1,Joe McKnight,Joe,McKnight,RB,2007,1,5,0.9997,USC,New Orleans,LA,30.032802,-89.975005,John Curtis
1,2,Lionel Breaux,Lionel,Breaux,WR,2007,305,3,0.8795,Ole Miss,New Orleans,LA,30.032802,-89.975005,McDonogh 35
2,3,Korey Williams,Korey,Williams,ILB,2007,519,3,0.8559,Southern Miss,New Orleans,LA,30.032802,-89.975005,Edna Karr
3,4,Tyler Stradford,Tyler,Stradford,WR,2007,523,3,0.8559,Oklahoma,New Orleans,LA,30.032802,-89.975005,O Perry Walker
4,5,Delvin Breaux,Delvin,Breaux,CB,2007,665,3,0.8479,LSU,New Orleans,LA,30.032802,-89.975005,McDonogh 35

In [58]:
drafted = pd.merge(recruits, draftees, how='inner', on='PLAYER')
#drafted = pd.merge(recruits, draftees, how='inner',left_on=['PLAYER','COLLEGE'], right_on=['PLAYER','SCHOOL'])
mask = drafted.duplicated('PLAYER', keep=False)
#drafted.to_csv('test2.csv')
drafted_dups = drafted[mask]
drafted_dups
drafted_dups_2 = drafted_dups.drop(drafted_dups[drafted_dups['COLLEGE'] != drafted_dups['SCHOOL']].index)
drafted_dups_2.drop_duplicates('PLAYER', keep='last')

,PLAYER,FIRST_NAME_x,LAST_NAME_x,POS_x,YEAR_x,RNK,STAR,247_SCORE,COLLEGE,CITY,...,LNG,HIGH_SCHOOL,YEAR_y,RND,PICK,FIRST_NAME_y,LAST_NAME_y,TM,POS_y,SCHOOL
26,Brandon Brooks,Brandon,Brooks,OT,2007,559,3,0.8556,Miami (OH),Milwaukee,...,-87.922497,Riverside,2012,3,76,Brandon,Brooks,HOU,G,Miami (OH)
47,Matt Jones,Matt,Jones,ATH,2012,159,4,0.9347,Florida,Seffner,...,-82.275647,Armwood,2015,3,95,Matt,Jones,WAS,RB,Florida
65,Steven Daniels,Steven,Daniels,ILB,2012,858,3,0.8510,Boston College,Cincinnati,...,-84.512460,Worcester Academy,2016,7,232,Steven,Daniels,WAS,ILB,Boston College
81,Malcolm Mitchell,Malcolm,Mitchell,ATH,2011,33,4,0.9810,Georgia,Valdosta,...,-83.278485,Valdosta,2016,4,112,Malcolm,Mitchell,NWE,WR,Georgia
87,Geno Smith,Geno,Smith,DUAL,2009,100,4,0.9540,West Virginia,Hollywood,...,-80.149490,Miramar,2013,2,39,Geno,Smith,NYJ,QB,West Virginia
90,Jonathan Williams,Jonathan,Williams,RB,2012,179,4,0.9276,Arkansas,Allen,...,-96.670550,Allen,2016,5,156,Jonathan,Williams,BUF,RB,Arkansas
100,Ryan Williams,Ryan,Williams,RB,2008,40,4,0.9787,Virginia Tech,Manassas,...,-77.482444,Stonewall Jackson,2011,2,38,Ryan,Williams,ARI,RB,Virginia Tech
132,Josh Robinson,Josh,Robinson,RB,2011,956,3,0.8366,Mississippi State,Franklinton,...,-90.153141,Franklinton,2015,6,205,Josh,Robinson,IND,RB,Mississippi State
138,James White,James,White,RB,2010,511,3,0.8733,Wisconsin,Fort Lauderdale,...,-80.143379,St. Thomas Aquinas,2014,4,130,James,White,NWE,RB,Wisconsin
157,Jamar Taylor,Jamar,Taylor,CB,2008,960,3,0.8333,Boise State,La Mesa,...,-117.023084,Helix,2013,2,54,Jamar,Taylor,MIA,DB,Boise State
160,Andrew Jackson,Andrew,Jackson,ILB,2010,2056,2,0.7889,Western Kentucky,Lakeland,...,-81.949804,Kathleen,2014,6,203,Andrew,Jackson,IND,LB,Western Kentucky
166,James Wright,James,Wright,WR,2010,321,4,0.8938,LSU,Belle Chasse,...,-89.990625,Belle Chasse,2014,7,239,James,Wright,CIN,WR,LSU
170,Steve Williams,Steve,Williams,CB,2009,136,4,0.9369,California,Dallas,...,-96.796856,Skyline,2013,5,145,Steve,Williams,SDG,DB,California
174,Mike Davis,Mike,Davis,RB,2012,47,4,0.9772,South Carolina,Stone Mountain,...,-84.145751,Stephenson,2015,4,126,Mike,Davis,SFO,RB,South Carolina
183,Nick Martin,Nick,Martin,OG,2011,529,3,0.8610,Notre Dame,Indianapolis,...,-86.158350,Bishop Chatard,2016,2,50,Nick,Martin,HOU,G,Notre Dame
196,Anthony Davis,Anthony,Davis,OT,2007,55,4,0.9760,Rutgers,Piscataway,...,-74.466041,Piscataway Twp,2010,1,11,Anthony,Davis,SFO,T,Rutgers
211,Anthony Brown,Anthony,Brown,ATH,2012,1315,3,0.8224,Purdue,Tampa,...,-82.458444,Hillsborough,2016,6,189,Anthony,Brown,DAL,CB,Purdue
214,Nick Perry,Nick,Perry,WDE,2008,60,4,0.9713,USC,Detroit,...,-83.056737,Martin Luther King,2012,1,28,Nick,Perry,GNB,DE,USC
226,Ryan Grant,Ryan,Grant,WR,2009,1727,2,0.7889,Tulane,Beaumont,...,-94.101846,West Brook,2014,5,142,Ryan,Grant,WAS,WR,Tulane
236,Derrick Morgan,Derrick,Morgan,SDE,2007,72,4,0.9655,Georgia Tech,Coatesville,...,-75.823836,Coatesville Area,2010,1,16,Derrick,Morgan,TEN,DE,Georgia Tech
253,Marcus Gilchrist,Marcus,Gilchrist,CB,2007,80,4,0.9596,Clemson,High Point,...,-82.647907,T Wingate Andrews,2011,2,50,Marcus,Gilchrist,SDG,DB,Clemson
265,Jeremy Hill,Jeremy,Hill,RB,2012,316,4,0.8994,LSU,Baton Rouge,...,-91.154551,Redemptorist,2014,2,55,Jeremy,Hill,CIN,RB,LSU
274,Michael Thomas,Michael,Thomas,WR,2011,765,3,0.8477,Ohio State,Woodland Hills,...,-118.605920,Taft,2016,2,47,Michael,Thomas,NOR,WR,Ohio State
290,Kevin Johnson,Kevin,Johnson,CB,2010,1579,3,0.8288,Wake Forest,Clarksville,...,-76.942918,River Hill,2015,1,16,Kevin,Johnson,HOU,CB,Wake Forest
294,Michael Sam,Michael,Sam,WDE,2009,1177,3,0.8368,Missouri,Hitchcock,...,-95.016037,Hitchcock,2014,7,249,Michael,Sam,STL,DE,Missouri
306,Xavier Rhodes,Xavier,Rhodes,WR,2009,897,3,0.8525,Florida State,Miami,...,-80.193659,Norland,2013,1,25,Xavier,Rhodes,MIN,DB,Florida State
308,Phillip Thomas,Phillip,Thomas,S,2007,1816,2,0.7444,Fresno State,Bakersfield,...,-119.019464,Bakersfield,2013,4,119,Phillip,Thomas,WAS,DB,Fresno State
310,Brandon Taylor,Brandon,Taylor,S,2008,168,4,0.9249,LSU,Franklinton,...,-90.153141,Franklinton,2012,3,73,Brandon,Taylor,SDG,DB,LSU
331,Michael Williams,Michael,Williams,TE,2008,208,4,0.9124,Alabama,Reform,...,-88.015301,Pickens County,2013,7,211,Michael,Williams,DET,TE,Alabama
347,Chris Jones,Chris,Jones,DT,2009,2126,2,0.7444,Bowling Green,Brownsburg,...,-86.397774,Brownsburg,2013,6,198,Chris,Jones,HOU,DT,Bowling Green
358,Aaron Williams,Aaron,Williams,CB,2008,98,4,0.9517,Texas,Austin,...,-97.743700,McNeil,2011,2,34,Aaron,Williams,BUF,DB,Texas
370,Ryan Murphy,Ryan,Murphy,S,2010,1456,3,0.8333,Oregon State,Oakland,...,-122.271356,Oakland Technical,2015,7,248,Ryan,Murphy,SEA,DB,Oregon State
418,Marcus Smith,Marcus,Smith,WDE,2010,593,3,0.8684,Louisville,Columbus,...,-84.987709,Hardaway,2014,1,26,Marcus,Smith,PHI,LB,Louisville
456,Michael Bennett,Michael,Bennett,DT,2011,49,4,0.9736,Ohio State,Dayton,...,-84.191607,Centerville,2015,6,180,Michael,Bennett,JAX,DT,Ohio State
482,Stedman Bailey,Stedman,Bailey,WR,2009,355,3,0.8875,West Virginia,Hollywood,...,-80.149490,Miramar,2013,3,92,Stedman,Bailey,STL,WR,West Virginia
485,Cedric Thompson,Cedric,Thompson,CB,2011,2153,2,0.7444,Minnesota,Calipatria,...,-115.549456,Calipatria,2015,5,150,Cedric,Thompson,MIA,FS,Minnesota
499,T.J. Jones,T.J.,Jones,WR,2010,87,4,0.9591,Notre Dame,Gainesville,...,-83.824066,Gainesville,2014,6,189,T.J.,Jones,DET,WR,Notre Dame
502,Oday Aboushi,Oday,Aboushi,OT,2009,568,3,0.8694,Virginia,Brooklyn,...,-73.949582,Xaverian,2013,5,141,Oday,Aboushi,NYJ,T,Virginia
526,Justin Gilbert,Justin,Gilbert,ATH,2010,251,4,0.9059,Oklahoma State,Huntsville,...,-95.550777,Huntsville,2014,1,8,Justin,Gilbert,CLE,DB,Oklahoma State
530,Marvin Jones,Marvin,Jones,WR,2008,182,4,0.9202,California,Rancho Cucamonga,...,-117.575174,Etiwanda,2012,5,166,Marvin,Jones,CIN,WR,California
585,Chris Carter,Chris,Carter,OLB,2007,848,3,0.8333,Fresno State,Fontana,...,-117.435048,Kaiser,2011,5,162,Chris,Carter,PIT,LB,Fresno State
642,Chris Smith,Chris,Smith,WDE,2010,641,3,0.8655,Arkansas,Mount Ulla,...,-80.726736,West Rowan,2014,5,159,Chris,Smith,JAX,DE,Arkansas
669,Chris Givens,Chris,Givens,RB,2008,1272,3,0.8111,Wake Forest,Wylie,...,-96.538879,Wylie,2012,4,96,Chris,Givens,STL,WR,Wake Forest
673,Kyle Fuller,Kyle,Fuller,CB,2010,1072,3,0.8510,Virginia Tech,Baltimore,...,-76.610759,Mount Saint Joseph,2014,1,14,Kyle,Fuller,CHI,DB,Virginia Tech
693,Brandon Thomas,Brandon,Thomas,OT,2009,250,4,0.9030,Clemson,Roebuck,...,-81.966214,Dorman,2014,3,100,Brandon,Thomas,SFO,OL,Clemson
739,Devin Smith,Devin,Smith,WR,2011,286,3,0.8895,Ohio State,Massillon,...,-81.521509,Washington,2015,2,37,Devin,Smith,NYJ,WR,Ohio State
749,Jordan Hicks,Jordan,Hicks,OLB,2010,7,5,0.9962,Texas,West Chester,...,-81.344278,Lakota West,2015,3,84,Jordan,Hicks,PHI,OLB,Texas
757,Austin Johnson,Austin,Johnson,DT,2012,991,3,0.8422,Penn State,Richland,...,-74.870724,St Augustine Preparatory School,2016,2,43,Austin,Johnson,TEN,NT,Penn State
796,Brandon Thompson,Brandon,Thompson,DT,2008,61,4,0.9713,Clemson,Thomasville,...,-83.978781,Thomasville,2012,3,93,Brandon,Thompson,CIN,DT,Clemson
806,Sean Porter,Sean,Porter,OLB,2009,955,3,0.8505,Texas A&M,Schertz,...,-98.269570,Samuel Clemens,2013,4,118,Sean,Porter,CIN,LB,Texas A&M
818,Ryan Griffin,Ryan,Griffin,TE,2008,1666,2,0.7667,Connecticut,Londonderry,...,-71.373953,Londonderry Senior,2013,6,201,Ryan,Griffin,HOU,TE,Connecticut
852,Chris Thompson,Chris,Thompson,RB,2009,179,4,0.9197,Florida State,Greenville,...,-83.629969,Madison County,2013,5,154,Chris,Thompson,WAS,RB,Florida State
864,Malcolm Johnson,Malcolm,Johnson,WR,2010,691,3,0.8653,Mississippi State,Tuscaloosa,...,-87.486218,Northridge,2015,6,195,Malcolm,Johnson,CLE,TE,Mississippi State
909,Duke Williams,Duke,Williams,ATH,2009,1700,2,0.7889,Nevada,Reno,...,-119.813674,Procter R Hug,2013,4,105,Duke,Williams,BUF,DB,Nevada
1002,Tyler Wilson,Tyler,Wilson,PRO,2008,127,4,0.9366,Arkansas,Greenwood,...,-94.255766,Greenwood,2013,4,112,Tyler,Wilson,OAK,QB,Arkansas
1010,Kenny Bell,Kenny,Bell,ATH,2010,568,3,0.8701,Nebraska,Boulder,...,-105.270546,Fairview,2015,5,162,Kenny,Bell,TAM,WR,Nebraska
1087,Devin Taylor,Devin,Taylor,WDE,2008,1139,3,0.8188,South Carolina,Beaufort,...,-80.669829,Battery Creek,2013,4,132,Devin,Taylor,DET,DE,South Carolina
1108,Trevardo Williams,Trevardo,Williams,SDE,2009,1656,3,0.8000,Connecticut,New Milford,...,-73.411765,Canterbury School,2013,4,124,Trevardo,Williams,HOU,DE,Connecticut
1231,Kevin Pierre-Louis,Kevin,Pierre-Louis,OLB,2010,245,4,0.9101,Boston College,Stamford,...,-73.538734,King & Low Heywood Thomas,2014,4,132,Kevin,Pierre-Louis,SEA,LB,Boston College
1237,Corey Robinson,Corey,Robinson,OT,2010,1631,3,0.8227,South Carolina,Havelock,...,-76.901446,Havelock,2015,7,240,Corey,Robinson,DET,T,South Carolina

In [54]:
drafted_no_duplicates = drafted.drop_duplicates('PLAYER', keep=False)
drafted_no_duplicates

,PLAYER,FIRST_NAME_x,LAST_NAME_x,POS_x,YEAR_x,RNK,STAR,247_SCORE,COLLEGE,CITY,...,LNG,HIGH_SCHOOL,YEAR_y,RND,PICK,FIRST_NAME_y,LAST_NAME_y,TM,POS_y,SCHOOL
0,Joe McKnight,Joe,McKnight,RB,2007,1,5,0.9997,USC,New Orleans,...,-89.975005,John Curtis,2010,4,112,Joe,McKnight,NYJ,RB,USC
1,Tyrann Mathieu,Tyrann,Mathieu,CB,2010,223,4,0.9132,LSU,New Orleans,...,-89.975005,St. Augustine,2013,3,69,Tyrann,Mathieu,ARI,DB,LSU
2,Trai Turner,Trai,Turner,OG,2011,355,3,0.8765,LSU,New Orleans,...,-89.975005,St. Augustine,2014,3,92,Trai,Turner,CAR,OL,LSU
3,Deion Jones,Deion,Jones,OLB,2012,378,3,0.8899,LSU,New Orleans,...,-89.975005,Jesuit,2016,2,52,Deion,Jones,ATL,OLB,LSU
4,Lorenzo Doss,Lorenzo,Doss,ATH,2012,1123,3,0.8354,Tulane,New Orleans,...,-89.975005,St. Augustine,2015,5,164,Lorenzo,Doss,DEN,CB,Tulane
5,Jimmy Clausen,Jimmy,Clausen,PRO,2007,2,5,0.9988,Notre Dame,Thousand Oaks,...,-118.910588,Oaks Christian,2010,2,48,Jimmy,Clausen,CAR,QB,Notre Dame
6,Casey Matthews,Casey,Matthews,ILB,2007,347,3,0.8764,Oregon,Thousand Oaks,...,-118.910588,Oaks Christian,2011,4,116,Casey,Matthews,PHI,LB,Oregon
7,Cassius Marsh,Cassius,Marsh,DT,2010,118,4,0.9441,UCLA,Thousand Oaks,...,-118.910588,Oaks Christian,2014,4,108,Cassius,Marsh,SEA,DE,UCLA
8,Jordan Payton,Jordan,Payton,WR,2012,135,4,0.9427,UCLA,Thousand Oaks,...,-118.910588,Oaks Christian,2016,5,154,Jordan,Payton,CLE,WR,UCLA
9,Eric Berry,Eric,Berry,CB,2007,3,5,0.9986,Tennessee,Fairburn,...,-84.581042,Creekside,2010,1,5,Eric,Berry,KAN,DB,Tennessee
10,Joshua Holsey,Joshua,Holsey,CB,2012,157,4,0.9358,Auburn,Fairburn,...,-84.581042,Creekside,2017,7,235,Joshua,Holsey,WAS,DB,Auburn
11,Marvin Austin,Marvin,Austin,DT,2007,4,5,0.9979,North Carolina,Washington,...,-77.036646,Ballou,2011,2,52,Marvin,Austin,NYG,DT,North Carolina
12,Arrelious Benn,Arrelious,Benn,WR,2007,12,5,0.9937,Illinois,Washington,...,-77.036646,Dunbar,2010,2,39,Arrelious,Benn,TAM,WR,Illinois
13,Jeremiah Attaochu,Jeremiah,Attaochu,OLB,2010,1073,3,0.8510,Georgia Tech,Washington,...,-77.036646,Archbishop Carroll,2014,2,50,Jeremiah,Attaochu,SDG,LB,Georgia Tech
14,Kevin Hogan,Kevin,Hogan,PRO,2011,356,3,0.8764,Stanford,Washington,...,-77.036646,Gonzaga,2016,5,162,Kevin,Hogan,KAN,QB,Stanford
15,Eddie Goldman,Eddie,Goldman,DT,2012,10,5,0.9944,Florida State,Washington,...,-77.036646,Friendship Academy,2015,2,39,Eddie,Goldman,CHI,DT,Florida State
16,Sean Davis,Sean,Davis,CB,2012,682,3,0.8657,Maryland,Washington,...,-77.036646,Maret School,2016,2,58,Sean,Davis,PIT,CB,Maryland
17,Ryan Mallett,Ryan,Mallett,PRO,2007,5,5,0.9978,Michigan,Texarkana,...,-94.047688,Texas High,2011,3,74,Ryan,Mallett,NWE,QB,Arkansas
18,Cobi Hamilton,Cobi,Hamilton,WR,2009,463,3,0.8764,Arkansas,Texarkana,...,-94.047688,Texas High,2013,6,197,Cobi,Hamilton,CIN,WR,Arkansas
19,Marqueston Huff,Marqueston,Huff,CB,2010,1223,3,0.8448,Wyoming,Texarkana,...,-94.047688,Liberty-Eylau,2014,4,122,Marqueston,Huff,TEN,DB,Wyoming
20,Nick Reed,Nick,Reed,FB,2012,1818,2,0.7942,SMU,Texarkana,...,-94.047688,Pleasant Grove,2009,7,247,Nick,Reed,SEA,DE,Oregon
21,Matt Kalil,Matt,Kalil,OT,2008,20,5,0.9892,USC,Anaheim,...,-117.911732,Servite,2012,1,4,Matt,Kalil,MIN,T,USC
22,Troy Niklas,Troy,Niklas,SDE,2011,179,4,0.9187,Notre Dame,Anaheim,...,-117.911732,Servite,2014,2,52,Troy,Niklas,ARI,TE,Notre Dame
23,Everson Griffen,Everson,Griffen,SDE,2007,9,5,0.9960,USC,Avondale,...,-112.340502,Agua Fria,2010,4,100,Everson,Griffen,MIN,DE,USC
24,Tommy Bohanon,Tommy,Bohanon,FB,2009,1265,3,0.8333,Wake Forest,North Fort Myers,...,-81.813010,North Fort Myers,2013,7,215,Tommy,Bohanon,NYJ,RB,Wake Forest
25,Tre Boston,Tre,Boston,CB,2010,818,3,0.8590,North Carolina,North Fort Myers,...,-81.813010,North Fort Myers,2014,4,128,Tre,Boston,CAR,DB,North Carolina
28,Kevin Zeitler,Kevin,Zeitler,OG,2008,691,3,0.8556,Wisconsin,Milwaukee,...,-87.922497,Wisconsin Lutheran,2012,1,27,Kevin,Zeitler,CIN,G,Wisconsin
29,Eric Murray,Eric,Murray,ATH,2012,2047,2,0.7791,Minnesota,Milwaukee,...,-87.922497,Riverside,2016,4,106,Eric,Murray,KAN,CB,Minnesota
30,Carlos Dunlap,Carlos,Dunlap,SDE,2007,14,5,0.9935,Florida,North Charleston,...,-79.974810,Fort Dorchester,2010,2,54,Carlos,Dunlap,CIN,DE,Florida
31,Robert Quinn,Robert,Quinn,WDE,2008,264,4,0.8993,North Carolina,North Charleston,...,-79.974810,Fort Dorchester,2011,1,14,Robert,Quinn,STL,DE,North Carolina
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1301,B.J. Goodson,B.J.,Goodson,ILB,2011,1143,3,0.8258,Clemson,Lamar,...,-80.062515,Lamar Hi,2016,4,109,B.J.,Goodson,NYG,OLB,Clemson
1302,Connor McGovern,Connor,McGovern,OG,2011,1181,3,0.8221,Missouri,Fargo,...,-96.789821,Shanley-sullivan Middle School,2016,5,144,Connor,McGovern,DEN,G,Missouri
1303,Benardrick McKinney,Benardrick,McKinney,ATH,2011,1200,3,0.8209,Mississippi State,Tunica,...,-90.382877,Rosa Fort,2015,2,43,Benardrick,McKinney,HOU,ILB,Mississippi State
1304,Travis Feeney,Travis,Feeney,S,2011,1214,3,0.8190,Washington,Pinole,...,-122.298859,Pinole Valley,2016,6,220,Travis,Feeney,PIT,OLB,Washington
1305,Will Holden,Will,Holden,OT,2012,923,3,0.8464,Vanderbilt,Green Cove Springs,...,-81.678147,Clay,2017,5,157,Will,Holden,ARI,T,Vanderbilt
1306,Paxton Lynch,Paxton,Lynch,PRO,2012,1894,2,0.7898,Memphis,Deltona,...,-81.263674,Trinity Christian Academy,2016,1,26,Paxton,Lynch,DEN,QB,Memphis
1307,Cory James,Cory,James,OLB,2011,2049,2,0.7593,Colorado State,Del Rio,...,-100.896761,Del Rio,2016,6,194,Cory,James,OAK,OLB,Colorado State
1308,Christian Covington,Christian,Covington,DT,2011,1735,2,0.7699,Rice,North Vancouver,...,-123.074341,Vancouver College Prep,2015,6,216,Christian,Covington,HOU,DT,Rice
1309,Jerald Hawkins,Jerald,Hawkins,OT,2012,350,4,0.8935,LSU,Baldwin,...,-87.732439,West St. Mary,2016,4,123,Jerald,Hawkins,PIT,T,LSU
1310,Chase Roullier,Chase,Roullier,OG,2012,1926,2,0.7881,Wyoming,Burnsville,...,-93.277723,Burnsville Senior,2017,6,199,Chase,Roullier,WAS,C,Wyoming
1311,Isaac Seumalo,Isaac,Seumalo,OG,2012,28,5,0.9876,Oregon State,Corvallis,...,-123.262044,Corvallis,2016,3,79,Isaac,Seumalo,PHI,G,Oregon State
1312,Devin Fuller,Devin,Fuller,ATH,2012,39,4,0.9812,UCLA,Westwood,...,-74.032640,Old Tappan,2016,7,238,Devin,Fuller,ATL,WR,UCLA
1313,Carlos Watkins,Carlos,Watkins,DT,2012,71,4,0.9666,Clemson,Forest City,...,-81.865103,Chase,2017,4,142,Carlos,Watkins,HOU,DT,Clemson
1314,Ricardo Louis,Ricardo,Louis,WR,2012,148,4,0.9393,Auburn,Miami Beach,...,-80.127270,Miami Beach Senior,2016,4,114,Ricardo,Louis,CLE,WR,Auburn
1315,David Reed,David,Reed,OLB,2012,2751,2,0.7398,Western Michigan,Miami Beach,...,-80.127270,Miami Beach Senior,2010,5,156,David,Reed,BAL,WR,Utah
1316,Vince Biegel,Vince,Biegel,OLB,2012,150,4,0.9388,Wisconsin,Wisconsin Rapids,...,-89.822877,Lincoln,2017,4,108,Vince,Biegel,GNB,LB,Wisconsin
1317,Taylor Decker,Taylor,Decker,OT,2012,163,4,0.9326,Ohio State,Vandalia,...,-84.198831,Butler,2016,1,16,Taylor,Decker,DET,T,Ohio State
1318,Adrian Colbert,Adrian,Colbert,S,2012,165,4,0.9324,Texas,Mineral Wells,...,-98.112822,Mineral Wells,2017,7,229,Adrian,Colbert,SFO,DB,Miami
1319,Vernon Butler,Vernon,Butler,SDE,2012,1835,2,0.7925,Louisiana Tech,Summit,...,-96.347513,North Pike,2016,1,30,Vernon,Butler,CAR,DT,Louisiana Tech
1320,Joey Hunt,Joey,Hunt,OC,2012,506,3,0.8782,TCU,El Campo,...,-96.269687,El Campo,2016,6,215,Joey,Hunt,SEA,C,TCU
1321,Kenneth Dixon,Kenneth,Dixon,RB,2012,912,3,0.8472,Louisiana Tech,Strong,...,-92.334864,Strong,2016,4,134,Kenneth,Dixon,BAL,RB,Louisiana Tech
1322,Maxx Williams,Maxx,Williams,TE,2012,1056,3,0.8388,Minnesota,Waconia,...,-93.786909,Waconia Senior,2015,2,55,Maxx,Williams,BAL,TE,Minnesota
1323,Dede Westbrook,Dede,Westbrook,WR,2012,1196,3,0.8312,Texas State,Cameron,...,-96.976930,Cameron Yoe,2017,4,110,Dede,Westbrook,JAX,WR,Oklahoma
1324,Obi Melifonwu,Obi,Melifonwu,S,2012,1377,3,0.8188,Connecticut,Grafton,...,-71.685624,Grafton Memorial Senior,2017,2,56,Obi,Melifonwu,OAK,S,Connecticut
1325,Justin Simmons,Justin,Simmons,S,2012,1443,3,0.8154,Boston College,Stuart,...,-80.251918,Martin County,2016,3,98,Justin,Simmons,DEN,FS,Boston College
1326,Tyrone Holmes,Tyrone,Holmes,SDE,2012,1498,3,0.8120,Montana,Eagle Point,...,-122.802818,Eagle Point,2016,6,181,Tyrone,Holmes,JAX,OLB,Montana
1327,Nick Vigil,Nick,Vigil,APB,2012,1617,3,0.8062,Utah State,Ogden,...,-111.973843,Fremont,2016,3,87,Nick,Vigil,CIN,ILB,Utah State
1328,Adam Gotsis,Adam,Gotsis,OT,2012,1677,3,0.8025,Georgia Tech,Abbotsford,...,-122.330017,Kew High School,2016,2,63,Adam,Gotsis,DEN,DT,Georgia Tech
1329,Taylor Moton,Taylor,Moton,OT,2012,2426,2,0.7643,Western Michigan,Okemos,...,-84.428183,Okemos,2017,2,64,Taylor,Moton,CAR,G,Western Michigan
1330,Darius Jackson,Darius,Jackson,S,2012,2687,2,0.7481,Eastern Michigan,Sparta,...,-89.701766,Sparta,2016,6,216,Darius,Jackson,DAL,RB,Eastern Michigan

In [9]:
drafted.groupby('STAR').count()

,PLAYER,FIRST_NAME_x,LAST_NAME_x,POS_x,YEAR_x,RNK,247_SCORE,COLLEGE,CITY,STATE,...,LNG,HIGH_SCHOOL,YEAR_y,RND,PICK,FIRST_NAME_y,LAST_NAME_y,TM,POS_y,SCHOOL
STAR,,,,,,,,,,,,,,,,,,,,,
2,216,216,216,216,216,216,216,216,216,216,...,216,216,216,216,216,216,216,216,216,216
3,621,621,621,621,621,621,621,621,621,621,...,621,621,621,621,621,621,621,621,621,621
4,386,386,386,386,386,386,386,386,386,386,...,386,386,386,386,386,386,386,386,386,386
5,108,108,108,108,108,108,108,108,108,108,...,108,108,108,108,108,108,108,108,108,108

In [10]:
recruits.groupby('STAR').count()

,PLAYER,FIRST_NAME,LAST_NAME,POS,YEAR,RNK,247_SCORE,COLLEGE,CITY,STATE,LAT,LNG,HIGH_SCHOOL
STAR,,,,,,,,,,,,,
1,27,27,27,27,27,27,27,27,27,27,27,27,27
2,5278,5278,5278,5278,5278,5278,5278,5278,5278,5278,5278,5278,5278
3,7675,7675,7675,7675,7675,7675,7675,7675,7675,7675,7675,7675,7675
4,1722,1722,1722,1722,1722,1722,1722,1722,1722,1722,1722,1722,1722
5,190,190,190,190,190,190,190,190,190,190,190,190,190

In [11]:
drafted.groupby(['SCHOOL']).count().sort_values('PLAYER', ascending=False)

,PLAYER,FIRST_NAME_x,LAST_NAME_x,POS_x,YEAR_x,RNK,STAR,247_SCORE,COLLEGE,CITY,...,LAT,LNG,HIGH_SCHOOL,YEAR_y,RND,PICK,FIRST_NAME_y,LAST_NAME_y,TM,POS_y
SCHOOL,,,,,,,,,,,,,,,,,,,,,
Alabama,46,46,46,46,46,46,46,46,46,46,...,46,46,46,46,46,46,46,46,46,46
Clemson,38,38,38,38,38,38,38,38,38,38,...,38,38,38,38,38,38,38,38,38,38
LSU,37,37,37,37,37,37,37,37,37,37,...,37,37,37,37,37,37,37,37,37,37
Florida State,34,34,34,34,34,34,34,34,34,34,...,34,34,34,34,34,34,34,34,34,34
Georgia,33,33,33,33,33,33,33,33,33,33,...,33,33,33,33,33,33,33,33,33,33
Ohio State,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,30
Florida,30,30,30,30,30,30,30,30,30,30,...,30,30,30,30,30,30,30,30,30,30
USC,29,29,29,29,29,29,29,29,29,29,...,29,29,29,29,29,29,29,29,29,29
Notre Dame,28,28,28,28,28,28,28,28,28,28,...,28,28,28,28,28,28,28,28,28,28
Mississippi State,28,28,28,28,28,28,28,28,28,28,...,28,28,28,28,28,28,28,28,28,28
Oklahoma,27,27,27,27,27,27,27,27,27,27,...,27,27,27,27,27,27,27,27,27,27
South Carolina,26,26,26,26,26,26,26,26,26,26,...,26,26,26,26,26,26,26,26,26,26
Miami,26,26,26,26,26,26,26,26,26,26,...,26,26,26,26,26,26,26,26,26,26
Arkansas,25,25,25,25,25,25,25,25,25,25,...,25,25,25,25,25,25,25,25,25,25
Stanford,23,23,23,23,23,23,23,23,23,23,...,23,23,23,23,23,23,23,23,23,23
UCLA,21,21,21,21,21,21,21,21,21,21,...,21,21,21,21,21,21,21,21,21,21
Missouri,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,20,20,20,20
California,20,20,20,20,20,20,20,20,20,20,...,20,20,20,20,20,20,20,20,20,20
Iowa,19,19,19,19,19,19,19,19,19,19,...,19,19,19,19,19,19,19,19,19,19
Texas,19,19,19,19,19,19,19,19,19,19,...,19,19,19,19,19,19,19,19,19,19
Louisville,19,19,19,19,19,19,19,19,19,19,...,19,19,19,19,19,19,19,19,19,19
Oregon,19,19,19,19,19,19,19,19,19,19,...,19,19,19,19,19,19,19,19,19,19
Wisconsin,19,19,19,19,19,19,19,19,19,19,...,19,19,19,19,19,19,19,19,19,19
Texas A&M,18,18,18,18,18,18,18,18,18,18,...,18,18,18,18,18,18,18,18,18,18
Michigan,18,18,18,18,18,18,18,18,18,18,...,18,18,18,18,18,18,18,18,18,18
Michigan State,18,18,18,18,18,18,18,18,18,18,...,18,18,18,18,18,18,18,18,18,18
Connecticut,17,17,17,17,17,17,17,17,17,17,...,17,17,17,17,17,17,17,17,17,17
Penn State,17,17,17,17,17,17,17,17,17,17,...,17,17,17,17,17,17,17,17,17,17
Auburn,17,17,17,17,17,17,17,17,17,17,...,17,17,17,17,17,17,17,17,17,17
Virginia Tech,16,16,16,16,16,16,16,16,16,16,...,16,16,16,16,16,16,16,16,16,16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Kent State,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Massachusetts,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Troy,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Middle Tennessee State,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Missouri Southern,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Ala-Birmingham,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
Western Illinois,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Tulsa,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Akron,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Montana,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Tennessee State,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Tenn-Martin,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Delaware,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Eastern Illinois,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Eastern Kentucky,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Kutztown Pennsylvania,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Liberty,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Louisiana-Lafayette,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Louisiana-Monroe,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Mars Hill,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
New Mexico State,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
North Alabama,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Northwestern State (LA),1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Pittsburg State,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Princeton,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
South Carolina State,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Southern Utah,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Tarleton State,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Tenn-Chattanooga,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
Youngstown State,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

In [12]:
five_drafted = drafted.loc[drafted['STAR'] == 5]
five_drafted.groupby('SCHOOL').count().sort_values('PLAYER',ascending=False).head(10)

,PLAYER,FIRST_NAME_x,LAST_NAME_x,POS_x,YEAR_x,RNK,STAR,247_SCORE,COLLEGE,CITY,...,LAT,LNG,HIGH_SCHOOL,YEAR_y,RND,PICK,FIRST_NAME_y,LAST_NAME_y,TM,POS_y
SCHOOL,,,,,,,,,,,,,,,,,,,,,
Alabama,10,10,10,10,10,10,10,10,10,10,...,10,10,10,10,10,10,10,10,10,10
Florida,10,10,10,10,10,10,10,10,10,10,...,10,10,10,10,10,10,10,10,10,10
USC,10,10,10,10,10,10,10,10,10,10,...,10,10,10,10,10,10,10,10,10,10
Florida State,10,10,10,10,10,10,10,10,10,10,...,10,10,10,10,10,10,10,10,10,10
Georgia,7,7,7,7,7,7,7,7,7,7,...,7,7,7,7,7,7,7,7,7,7
Clemson,5,5,5,5,5,5,5,5,5,5,...,5,5,5,5,5,5,5,5,5,5
Miami,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
Ohio State,4,4,4,4,4,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,4
Texas,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3
LSU,3,3,3,3,3,3,3,3,3,3,...,3,3,3,3,3,3,3,3,3,3

In [13]:
five_recruited = recruits.loc[recruits['STAR'] == 5]
five_recruited.groupby('COLLEGE').count().sort_values('PLAYER', ascending=False).head(10)

,PLAYER,FIRST_NAME,LAST_NAME,POS,YEAR,RNK,STAR,247_SCORE,CITY,STATE,LAT,LNG,HIGH_SCHOOL
COLLEGE,,,,,,,,,,,,,
Florida,21,21,21,21,21,21,21,21,21,21,21,21,21
USC,18,18,18,18,18,18,18,18,18,18,18,18,18
Florida State,17,17,17,17,17,17,17,17,17,17,17,17,17
Alabama,15,15,15,15,15,15,15,15,15,15,15,15,15
Texas,14,14,14,14,14,14,14,14,14,14,14,14,14
Georgia,13,13,13,13,13,13,13,13,13,13,13,13,13
Ohio State,10,10,10,10,10,10,10,10,10,10,10,10,10
LSU,9,9,9,9,9,9,9,9,9,9,9,9,9
Notre Dame,8,8,8,8,8,8,8,8,8,8,8,8,8
Miami,7,7,7,7,7,7,7,7,7,7,7,7,7

In [53]:
four_drafted = drafted.loc[drafted['STAR'] == 4]
four_drafted.groupby('SCHOOL').count().sort_values('PLAYER',ascending=False).head(10)

,PRIMARY_KEY_x,PLAYER,FIRST_NAME_x,LAST_NAME_x,POS_x,YEAR_x,RNK,STAR,247_SCORE,COLLEGE,...,LNG,HIGH_SCHOOL,PRIMARY_KEY_y,YEAR_y,RND,PICK,FIRST_NAME_y,LAST_NAME_y,TM,POS_y
SCHOOL,,,,,,,,,,,,,,,,,,,,,
Alabama,25,25,25,25,25,25,25,25,25,25,...,25,25,25,25,25,25,25,25,25,25
LSU,21,21,21,21,21,21,21,21,21,21,...,21,21,21,21,21,21,21,21,21,21
Notre Dame,18,18,18,18,18,18,18,18,18,18,...,18,18,18,18,18,18,18,18,18,18
USC,15,15,15,15,15,15,15,15,15,15,...,15,15,15,15,15,15,15,15,15,15
Oklahoma,15,15,15,15,15,15,15,15,15,15,...,15,15,15,15,15,15,15,15,15,15
Georgia,15,15,15,15,15,15,15,15,15,15,...,15,15,15,15,15,15,15,15,15,15
Clemson,15,15,15,15,15,15,15,15,15,15,...,15,15,15,15,15,15,15,15,15,15
Florida,14,14,14,14,14,14,14,14,14,14,...,14,14,14,14,14,14,14,14,14,14
Ohio St.,14,14,14,14,14,14,14,14,14,14,...,14,14,14,14,14,14,14,14,14,14
UCLA,13,13,13,13,13,13,13,13,13,13,...,13,13,13,13,13,13,13,13,13,13

In [55]:
four_recruited = recruits.loc[recruits['STAR'] == 4]
four_recruited.groupby('COLLEGE').count().sort_values('PLAYER', ascending=False).head(10)

,PRIMARY_KEY,PLAYER,FIRST_NAME,LAST_NAME,POS,YEAR,RNK,STAR,247_SCORE,CITY,STATE,LAT,LNG,HIGH_SCHOOL
COLLEGE,,,,,,,,,,,,,,
Texas,88,88,88,88,88,88,88,88,88,88,88,88,88,88
Alabama,79,79,79,79,79,79,79,79,79,79,79,79,79,79
LSU,71,71,71,71,71,71,71,71,71,71,71,71,71,71
Florida,68,68,68,68,68,68,68,68,68,68,68,68,68,68
USC,65,65,65,65,65,65,65,65,65,65,65,65,65,65
Notre Dame,63,63,63,63,63,63,63,63,63,63,63,63,63,63
Ohio State,63,63,63,63,63,63,63,63,63,63,63,63,63,63
Michigan,60,60,60,60,60,60,60,60,60,60,60,60,60,60
Oklahoma,60,60,60,60,60,60,60,60,60,60,60,60,60,60
Auburn,52,52,52,52,52,52,52,52,52,52,52,52,52,52

In [25]:
test = drafted['STAR'].groupby(drafted['SCHOOL']).value_counts()
df_drafted_stars = test.to_frame()
df_drafted_stars = df_drafted_stars.rename(columns={'STAR':'#drafted'})
df_drafted_stars = df_drafted_stars.reset_index()
df_drafted_stars.head(10)

           SCHOOL  STAR  #drafted
0           Akron     2         1
1  Ala-Birmingham     2         2
2         Alabama     4        25
3         Alabama     5        10
4         Alabama     3         9
5         Alabama     2         2
6         Arizona     3         7
7         Arizona     4         2
8   Arizona State     3         3
9   Arizona State     4         3

In [29]:
school_stars = recruits['STAR'].groupby(recruits['COLLEGE']).value_counts()
df_school_stars = school_stars.to_frame()
df_school_stars = df_school_stars.rename(columns={'STAR':'#recruited'})
df_school_stars = df_school_stars.reset_index()
df_school_stars.head(15)

              COLLEGE  STAR  #recruited
0           Air Force     2          79
1           Air Force     3          14
2           Air Force     1           2
3               Akron     2          88
4               Akron     3          29
5             Alabama     4          79
6             Alabama     3          50
7             Alabama     5          15
8             Alabama     2           1
9       Alabama State     2           1
10  Appalachian State     2           4
11  Appalachian State     3           2
12            Arizona     3          82
13            Arizona     2          12
14            Arizona     4          10

In [28]:
star_merge = pd.merge(df_drafted_stars, df_school_stars, how='left', left_on=['SCHOOL','STAR'], right_on=['COLLEGE','STAR'])
star_merge['COLLEGE'].fillna('N/R', inplace=True)
star_merge['#recruited'].fillna(0, inplace=True)
star_merge['#recruited'] = star_merge['#recruited'].astype(int)
star_merge

               SCHOOL  STAR  #drafted           COLLEGE  #recruited
0               Akron     2         1             Akron          88
1      Ala-Birmingham     2         2               N/R           0
2             Alabama     4        25           Alabama          79
3             Alabama     5        10           Alabama          15
4             Alabama     3         9           Alabama          50
5             Alabama     2         2           Alabama           1
6             Arizona     3         7           Arizona          82
7             Arizona     4         2           Arizona          10
8       Arizona State     3         3     Arizona State          87
9       Arizona State     4         3     Arizona State          11
10      Arizona State     5         1     Arizona State           1
11           Arkansas     3        16          Arkansas         111
12           Arkansas     4         7          Arkansas          21
13           Arkansas     2         1          Arkansas          13
14           Arkansas     5         1          Arkansas           1
15     Arkansas State     2         3    Arkansas State          78
16     Arkansas State     3         1    Arkansas State          33
17             Auburn     4        10            Auburn          52
18             Auburn     3         4            Auburn          82
19             Auburn     2         2            Auburn           8
20             Auburn     5         1            Auburn           3
21                BYU     4         2               N/R           0
22                BYU     3         1               N/R           0
23         Ball State     3         2        Ball State          28
24             Baylor     3         6            Baylor          83
25             Baylor     4         4            Baylor          11
26             Baylor     2         3            Baylor          17
27             Baylor     5         1               N/R           0
28        Boise State     3         9       Boise State          67
29        Boise State     2         4       Boise State          40
..                ...   ...       ...               ...         ...
293          Virginia     3         6          Virginia         103
294          Virginia     4         3          Virginia          18
295     Virginia Tech     3         8     Virginia Tech         106
296     Virginia Tech     4         6     Virginia Tech          21
297     Virginia Tech     2         1     Virginia Tech          12
298     Virginia Tech     5         1     Virginia Tech           1
299       Wake Forest     3         8       Wake Forest          84
300       Wake Forest     2         2       Wake Forest          23
301        Washington     3         8        Washington          99
302        Washington     4         3        Washington          23
303        Washington     2         1        Washington          13
304        Washington     5         1        Washington           1
305  Washington State     3         2  Washington State          81
306  Washington State     2         1  Washington State          32
307  Washington State     4         1  Washington State           1
308     West Virginia     3        10     West Virginia          96
309     West Virginia     2         3     West Virginia          19
310     West Virginia     4         3     West Virginia          14
311  Western Illinois     2         1               N/R           0
312  Western Kentucky     2         3  Western Kentucky          36
313  Western Kentucky     3         1  Western Kentucky          14
314  Western Kentucky     4         1               N/R           0
315  Western Michigan     2         3  Western Michigan          86
316  Western Michigan     3         3  Western Michigan          45
317         Wisconsin     3        13         Wisconsin          90
318         Wisconsin     2         3         Wisconsin          15
319         Wisconsin     4         3         Wisconsin          13
320           Wyoming     2         2           Wyoming          77
321           Wyoming     3         1           Wyoming          32
322  Youngstown State     3         1               N/R           0

[323 rows x 5 columns]